In [1]:
import numpy as np

In [2]:
# This is one dimensional array 
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
# This is two dimensional array 
a=np.array([[1,2,3,4],[5,6,7,8]])
a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# This is three dimensional array 
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [5]:
# It will return the shape of the array
a.shape

(1, 3, 4)

In [6]:
# It will return the dimension of the array
a.ndim

3

In [7]:
# It will return total number of element in the array
a.size

12

In [8]:
# It converts rows into column and column into rows
a.T

array([[[ 1],
        [ 5],
        [ 9]],

       [[ 2],
        [ 6],
        [10]],

       [[ 3],
        [ 7],
        [11]],

       [[ 4],
        [ 8],
        [12]]])

In [9]:
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

Function in Numpy

In [10]:
# Here are using arange fucntion for creating array
# It works same as the range fucntion works
m=np.arange(1,13).reshape(4,3)
n=np.arange(21,33).reshape(4,3)

In [11]:
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
n

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [13]:
# This function is used to add two array and 
# axis value is used to specify the way we have to
# add the array  where '0' stands for column
# and '1'  stands for row 

np.concatenate([m,n],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [14]:
np.concatenate([m,n],axis=1)

array([[ 1,  2,  3, 21, 22, 23],
       [ 4,  5,  6, 24, 25, 26],
       [ 7,  8,  9, 27, 28, 29],
       [10, 11, 12, 30, 31, 32]])

In [15]:
# Here are using arange fucntion for creating array
# It works same as the range fucntion works
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [16]:
# This function is also used to add the value 
# but here the value will be added at the end 
# as we are not specifying the index number
np.append(a,[5,6])

array([1, 2, 3, 4, 5, 6])

In [17]:
# for adding the value from array we have 
# to specify the index number and  value
np.insert(a,1,8)

array([1, 8, 2, 3, 4])

In [18]:
# for deleting the value from array we have 
# to specify the index number of value
np.delete(a,[1])

array([1, 3, 4])

In [19]:
# create empty array
np.empty(shape=(4,5),dtype=int)

array([[          0,          32,  1936532091,  1684627303,   841103906],
       [ 1664181092,   828727860,   875968097,  1647653168,  1714447671],
       [ 1916285340, -2147469520,   573584949,  1937056300,  1634628197],
       [  975332717,  1702065442,  1835101810,   573317733,  1936942451]])

In [20]:
# create array having all element as 1
np.ones(shape=(4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
# create array having all element as =0
np.zeros(shape=(4,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
# create identity array
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# create array having same entries
np.full((4,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [24]:
# create array having specified difference among them
np.linspace(1,20,4)

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [25]:
m=np.arange(1,13)
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Slicing of 1D array

In [26]:
# Here we are retreiving the element by providing the index number
m[:5:3]

array([1, 4])

In [27]:
m[3::2]

array([ 4,  6,  8, 10, 12])

In [28]:
m[::5]

array([ 1,  6, 11])

Indexing of 1D array

In [29]:
# Here we are retreiving the element by providing the index number
m[1]

2

In [30]:
m[5]

6

In [31]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Indexing

In [55]:
#Here we are retrieving the value of '0' row and '0' column
a[0,0]

1

In [56]:
#Here we are retrieving the value of '1' row and '3' column
a[1][3]

8

Slicing

In [59]:
#Here we are retrieving the value from 1 row and 1,2 column value

a[1,1:3]

array([6, 7])

In [60]:
#Here we are retrieving the value from both row and 3 column value
a[0:2,3]

array([4, 8])

In [61]:
#Here we are retrieving the value from both row and 0 column value
a[0:2,0:1]

array([[1],
       [5]])

In [51]:
#Here we are retrieving the value from both row and 0,1,2 column value
a[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [67]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
a>2

array([[False, False,  True,  True],
       [ True,  True,  True,  True]])

In [69]:
#Retreive all values greater than 2
a[a>2]

array([3, 4, 5, 6, 7, 8])

In [82]:
#Retreive all values smaller than 4
a[a<4]

array([1, 2, 3])

In [83]:
b=np.array(['Jagdish','tejas','dhaval','bhavesh','montu','bipin','Jagdish'])
b

array(['Jagdish', 'tejas', 'dhaval', 'bhavesh', 'montu', 'bipin',
       'Jagdish'], dtype='<U7')

In [84]:
#Retreive all value having name rohit
# As below we can see all values are false
# as no value having name rohit
b=='rohit'

array([False, False, False, False, False, False, False])

In [85]:
#Retreive all value having name dhaval
b[b=='dhaval']

array(['dhaval'], dtype='<U7')

In [86]:
#Retreive all value having name tejas
b[b!='tejas']

array(['Jagdish', 'dhaval', 'bhavesh', 'montu', 'bipin', 'Jagdish'],
      dtype='<U7')

In [88]:
#Retreive all value having name montu or Jagdish
b[(b=='montu') | (b=='Jagdish')]

array(['Jagdish', 'montu', 'Jagdish'], dtype='<U7')

In [91]:
#Retreive all values without repetition
np.unique(b)

array(['Jagdish', 'bhavesh', 'bipin', 'dhaval', 'montu', 'tejas'],
      dtype='<U7')

Statistical function

In [96]:
a=np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [97]:
# Retreive the smallest value from array
a.min()

1

In [98]:
# Retreive the greatest value from array
a.max()

14

In [100]:
# Retreive the standard deviation value from array
a.std()

4.031128874149275

In [106]:
# Retreive the mean value from array
a.mean()

7.5

In [108]:
# Retreive the addition of all value from array
a.sum()

105

In [110]:
# Adding 12 to all value of array
a+12

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [95]:
b=np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
b.max()

12

In [111]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [113]:
# Retrive the one dimensional array
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Arithmetic function

In [118]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
b=np.arange(21,33).reshape(3,4)
b

array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [120]:
# Addition of array a and b
np.add(a,b)

array([[22, 24, 26, 28],
       [30, 32, 34, 36],
       [38, 40, 42, 44]])

In [121]:
# Substraction of array a and b
np.subtract(a,b)

array([[-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20]])

In [123]:
# Multiplication of array a and b
np.multiply(a,b)

array([[ 21,  44,  69,  96],
       [125, 156, 189, 224],
       [261, 300, 341, 384]])

In [126]:
# dividing of array b by a
np.divide(b,a)

array([[21.        , 11.        ,  7.66666667,  6.        ],
       [ 5.        ,  4.33333333,  3.85714286,  3.5       ],
       [ 3.22222222,  3.        ,  2.81818182,  2.66666667]])

In [132]:
# cross product of array a and b
np.kron(a,b)

array([[ 21,  22,  23,  24,  42,  44,  46,  48,  63,  66,  69,  72,  84,
         88,  92,  96],
       [ 25,  26,  27,  28,  50,  52,  54,  56,  75,  78,  81,  84, 100,
        104, 108, 112],
       [ 29,  30,  31,  32,  58,  60,  62,  64,  87,  90,  93,  96, 116,
        120, 124, 128],
       [105, 110, 115, 120, 126, 132, 138, 144, 147, 154, 161, 168, 168,
        176, 184, 192],
       [125, 130, 135, 140, 150, 156, 162, 168, 175, 182, 189, 196, 200,
        208, 216, 224],
       [145, 150, 155, 160, 174, 180, 186, 192, 203, 210, 217, 224, 232,
        240, 248, 256],
       [189, 198, 207, 216, 210, 220, 230, 240, 231, 242, 253, 264, 252,
        264, 276, 288],
       [225, 234, 243, 252, 250, 260, 270, 280, 275, 286, 297, 308, 300,
        312, 324, 336],
       [261, 270, 279, 288, 290, 300, 310, 320, 319, 330, 341, 352, 348,
        360, 372, 384]])

In [143]:
# return power 2 to all values
np.power(a,2)

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]], dtype=int32)

In [139]:
a=np.arange(1,13).reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [141]:
b=np.arange(21,33).reshape(3,4)
b

array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [142]:
# dot product of a and b 
# In dot product  column value of 1 array should same to row 
# value of 2 array
np.dot(a,b)

array([[158, 164, 170, 176],
       [383, 398, 413, 428],
       [608, 632, 656, 680],
       [833, 866, 899, 932]])